version: "2"

services:
  neo4j.qc:
    container_name: neo4j.qc
    image: agrdocker/agr_neo4j_qc_data_image:develop
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - esnet
    environment:
      - NEO4J_dbms_memory_heap_maxSize=4096
  agr_qc:
    image: "${REG}/agr_qc_run:develop"
    networks:
      - esnet
    environment:
     - NEO4J_HOST=neo4j.qc
     - NEO4J_PORT=7687

networks:
  esnet:
